package com.newt.dao.model;

import java.io.Serializable;

public class Car implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.id
     *
     * @mbggenerated Tue May 03 10:40:55 IST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.make
     *
     * @mbggenerated Tue May 03 10:40:55 IST 2016
     */
    private String make;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.model
     *
     * @mbggenerated Tue May 03 10:40:55 IST 2016
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.year
     *
     * @mbggenerated Tue May 03 10:40:55 IST 2016
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car
     *
     * @mbggenerated Tue May 03 10:40:55 IST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.id
     *
     * @return the value of car.id
     *
     * @mbggenerated Tue May 03 10:40:55 IST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.id
     *
     * @param id the value for car.id
     *
     * @mbggenerated Tue May 03 10:40:55 IST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.make
     *
     * @return the value of car.make
     *
     * @mbggenerated Tue May 03 10:40:55 IST 2016
     */
    public String getMake() {
        return make;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.make
     *
     * @param make the value for car.make
     *
     * @mbggenerated Tue May 03 10:40:55 IST 2016
     */
    public void setMake(String make) {
        this.make = make == null ? null : make.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.model
     *
     * @return the value of car.model
     *
     * @mbggenerated Tue May 03 10:40:55 IST 2016
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.model
     *
     * @param model the value for car.model
     *
     * @mbggenerated Tue May 03 10:40:55 IST 2016
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.year
     *
     * @return the value of car.year
     *
     * @mbggenerated Tue May 03 10:40:55 IST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.year
     *
     * @param year the value for car.year
     *
     * @mbggenerated Tue May 03 10:40:55 IST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }
}